version: 2.0
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/clagraff/gowebauth
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -v -covermode=atomic -coverprofile coverage.out ./...
      - persist_to_workspace:
          root: /go/src/github.com/clagraff/gowebauth
          paths:
            - coverage.out

  coverage:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/clagraff/gowebauth
    steps:  
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls
      - run: goveralls -coverprofile=/tmp/workspace/coverage.out -service=circle-ci

  linting:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/clagraff/gowebauth
    steps:
      - checkout
      - run: go get -u gopkg.in/alecthomas/gometalinter.v2
      - run: gometalinter.v2 --install
      - run: gometalinter.v2 --deadline 1m --enable-all --disable gochecknoglobals --disable gocyclo --exclude=".*_test.go" ./...

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - coverage:
          requires:
            - test
      - linting
